/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Sudoku;

import org.junit.Test;
import static org.junit.Assert.*;

public class SpeedupTesting {
    @Test public void testSerialVersion() {
        
    }
}
